apiVersion: v1
kind: Service
metadata:
  name: {{ include "acmeair.fullname" . }}-booking-service
  labels:
    {{- include "acmeair.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9080
      targetPort: 9080
      protocol: TCP
  selector:
    name: {{ include "acmeair.fullname" . }}-booking-deployment
