apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations:
    template.openshift.io/expose-admin_password: '{.data[''database-admin-password'']}'
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  name: {{ include "acmeair.fullname" . }}-booking-db
data:
  #database-admin-password: dzNmT1RVbjFFeVRxaWtLcg==
  #database-name: YWNtZWFpcl9mbGlnaHRkYg==
  #database-password: VGYxZXBoQXZxcmJLSHNrRA==
  #database-user: dXNlclNNUA==
  database-admin-password: {{ default (randAlphaNum 16) .Values.acmeairBooking.database.adminPassword | b64enc | quote }}
  database-name: {{ default ("acmeair-bookingdb") .Values.acmeairBooking.database.name | b64enc | quote }}
  database-password: {{ default (randAlphaNum 16) .Values.acmeairBooking.database.password | b64enc | quote }}
  database-user: {{ default (randAlphaNum 5) .Values.acmeairBooking.database.user | b64enc | quote }} 