apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  rules:
    - host: {{ .Values.service.hostname }}
      http:
        paths:
          - backend:
              serviceName: {{ template "fullname" . }}
              servicePort: {{ .Values.service.port }}