###############################################################################
############################## LabWeb #########################################
###############################################################################

###############################################################################
## Common image variables
###############################################################################

## Architecture - e.g. amd64, s390x, ppc64le. Specific worker node architecture
## to deploy to.
## You can use kubectl version command to determine the architecture on the
## desired worker node.

# Specify architecture (amd64, ppc64le, s390x) and weight to be  used for scheduling as follows :
#   0 - Do not use
#   1 - Least preferred
#   2 - No preference
#   3 - Most preferred
arch:
  amd64: "2 - No preference"
  ppc64le: "2 - No preference"
# s390x: "2 - No preference"

image:
  repository: registry.gitlab.com/pslc/docker/labweb
  tag: "2.1"
  pullPolicy: IfNotPresent
  secret: pslc-gitlab.regkey

###############################################################################
## Persistence Storage
###############################################################################

## Persistence enabled by default
## global persistence settings
#persistence:
#  enabled: false
#  useDynamicProvisioning: false

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 200Mi
    cpu: 200m
  limits:
    memory: 2Gi
    cpu: 16000m

service:
  name: http
  type: ClusterIP
  port: 8080
  hostname:
