apiVersion: v1
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous,IgnoreDifference=/spec/template/spec/containers/0/image
    labels:
      app.kubernetes.io/component: proxy
      app.kubernetes.io/name: haproxy-lb
      app.kubernetes.io/part-of: haproxy
      app: haproxy
    name: haproxy
  spec:
    replicas: 1
    revisionHistoryLimit: 3
    selector:
      app: haproxy-lb
      deploymentconfig: haproxy-lb
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
          argocd.argoproj.io/sync-options: Validate=false
          argocd.argoproj.io/compare-options: IgnoreExtraneous,IgnoreDifference=/spec/containers/0/image
        creationTimestamp: null
        labels:
          app: haproxy-lb
          deploymentconfig: haproxy-lb
      spec:
        containers:
        - image: haproxy:latest
          imagePullPolicy: Always
          name: haproxy-lb
          ports:
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          volumeMounts:
          - mountPath: /etc/haproxy
            name: config
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            items:
            - key: haproxy
              path: haproxy.cfg
            name: haproxy
          name: config
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - haproxy-lb
        from:
          kind: ImageStreamTag
          name: haproxy:latest
      type: ImageChange
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
